// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfPIulsif4iXDesx7TIR8c2phMo_TV6HU',
    appId: '1:483352088089:web:19997432737416b81da488',
    messagingSenderId: '483352088089',
    projectId: 'feedhub-f42a9',
    authDomain: 'feedhub-f42a9.firebaseapp.com',
    storageBucket: 'feedhub-f42a9.appspot.com',
    measurementId: 'G-HJBFN6E89N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo5XLxO6SeTzm9ySX2Vrqg1xCq89iFBOY',
    appId: '1:483352088089:android:86bb630b26e5b35b1da488',
    messagingSenderId: '483352088089',
    projectId: 'feedhub-f42a9',
    storageBucket: 'feedhub-f42a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo5XLxO6SeTzm9ySX2Vrqg1xCq89iFBOY',
    appId: '1:483352088089:ios:4910c7fa2d1485a91da488',
    messagingSenderId: '483352088089',
    projectId: 'feedhub-f42a9',
    storageBucket: 'feedhub-f42a9.appspot.com',
    iosClientId: '483352088089-15hrp2i6l2j8ogcivahr1ha4af7184u4.apps.googleusercontent.com',
    iosBundleId: 'com.citizenraf.feedhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo5XLxO6SeTzm9ySX2Vrqg1xCq89iFBOY',
    appId: '1:483352088089:ios:4910c7fa2d1485a91da488',
    messagingSenderId: '483352088089',
    projectId: 'feedhub-f42a9',
    storageBucket: 'feedhub-f42a9.appspot.com',
    iosClientId: '483352088089-15hrp2i6l2j8ogcivahr1ha4af7184u4.apps.googleusercontent.com',
    iosBundleId: 'com.citizenraf.feedhub',
  );
}
