// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMtACai6PpiB29tWVibWdl3y0dbWirdGM',
    appId: '1:944602773348:web:c356e6bc510494b9342c71',
    messagingSenderId: '944602773348',
    projectId: 'feed-hub-5dab3',
    authDomain: 'feed-hub-5dab3.firebaseapp.com',
    storageBucket: 'feed-hub-5dab3.appspot.com',
    measurementId: 'G-0CJB4H2HG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvkpw74x3eGzVXlOHjTysV9ZYNW4IySYQ',
    appId: '1:944602773348:android:e36f9b9985b9eb52342c71',
    messagingSenderId: '944602773348',
    projectId: 'feed-hub-5dab3',
    storageBucket: 'feed-hub-5dab3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVb1fb-fD6D8Adgu7k74aqe7Vr-lck9v8',
    appId: '1:944602773348:ios:5ef2e77352b1565c342c71',
    messagingSenderId: '944602773348',
    projectId: 'feed-hub-5dab3',
    storageBucket: 'feed-hub-5dab3.appspot.com',
    iosClientId: '944602773348-oem2i0fof3j76i8moupm5tbfauv7eqj0.apps.googleusercontent.com',
    iosBundleId: 'com.example.feedHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVb1fb-fD6D8Adgu7k74aqe7Vr-lck9v8',
    appId: '1:944602773348:ios:5ef2e77352b1565c342c71',
    messagingSenderId: '944602773348',
    projectId: 'feed-hub-5dab3',
    storageBucket: 'feed-hub-5dab3.appspot.com',
    iosClientId: '944602773348-oem2i0fof3j76i8moupm5tbfauv7eqj0.apps.googleusercontent.com',
    iosBundleId: 'com.example.feedHub',
  );
}
